packages:
  - "."

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  'eslint-plugin-barrel-files>oxc-resolver': 11.19.1
lockfile: true
allowBuilds:
  '@swc/core': false
  esbuild: false
  unrs-resolver: false
